SRC=Graph Label GraphUtil Fuel MkGraph Dataflow
HOOPL=Compiler/Hoopl
HS=${SRC:%=$HOOPL/%.hs}
O=${SRC:%=$HOOPL/%.o}

all:V: $O


%.o: %.hs
	ghc --make -c $prereq


clean:V:
	rm -f $HOOPL/*.o
	rm -f $HOOPL/*.hi
	rm -f *~ $HOOPL/*~
